os:
  - linux
language: node_js
node_js:
  - "10"
dist: bionic
sudo: required
services:
  - xvfb
addons:
  chrome: stable
before_script:
  - export DISPLAY=:99.0
before_install:
  - sudo apt-get install -y rpm
install:
  - npm set progress=false
  - npm install
script:
  - npm run electron:linux
deploy:
  - provider: releases
    api_key: $GITHUB_KEY
    file_glob: true
    file:
      - "release/violyOS Store-*.AppImage"
      - "release/violyOS Store_*_amd64.deb"
      - "release/violyOS Store-*.rpm"
      - "release/violyOS Store-*.tar.gz"
    skip_cleanup: true
    on:
      branch: master
      tags: true
